#!/bin/bash

set -v

DIR="$(dirname "$0")"
. "${DIR}/config"

# Install Istio CRDs
kubectl apply -f "https://raw.githubusercontent.com/nikhilbarthwal/istio/main/istio-crds.yaml"

# Install Istio
kubectl apply -f "https://raw.githubusercontent.com/nikhilbarthwal/istio/main/istio-minimal.yaml"

# Check all Istio pods have STATUS 'Running'
kubectl get pods -n istio-system

